# Generated by Django 3.0.8 on 2020-07-22 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0002_delete_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='mac',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
