# Generated by Django 3.0.8 on 2020-07-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0005_channel_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='number',
        ),
    ]
