# Generated by Django 3.0.8 on 2020-07-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
