# Generated by Django 3.0.8 on 2020-07-23 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0003_node_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch', models.CharField(max_length=255, unique=True)),
                ('txpkt_cnt', models.CharField(max_length=255)),
                ('crcok_cnt', models.CharField(max_length=255)),
                ('crcerr_cnt', models.CharField(max_length=255)),
                ('avg_sig_rssi', models.CharField(max_length=255)),
                ('avg_noise_rssi', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['ch'],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='number',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='mac',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
