# Generated by Django 3.0.8 on 2020-07-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0011_auto_20200723_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p2p.Node'),
            preserve_default=False,
        ),
    ]
