# Generated by Django 3.0.5 on 2020-04-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_addr',
            field=models.DecimalField(decimal_places=0, max_digits=16),
        ),
    ]
